version: "3.8"

services:
  frontend:
    build:
      context: ./Front-End
    ports:
      - "9000:5173"  # Expose frontend React app on port 9000
    networks:
      - app-network
    depends_on:
      - product-service
      - user-service
      - cart-service
      - admin-service
      - payment-gateway

  admin-service:
    build:
      context: ./Admin
    ports:
      - "9004:3004"  # Expose admin service on port 9004
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  cart-service:
    build:
      context: ./Cart
    ports:
      - "9003:3003"  # Expose cart service on port 9003
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  product-service:
    build:
      context: ./Product
    ports:
      - "9002:3002"  # Expose product service on port 9002
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  user-service:
    build:
      context: ./User
    ports:
      - "9001:3001"  # Expose user service on port 9001
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  payment-gateway:
    build:
      context: ./Payment-Gateway
    ports:
      - "7000:7000"  # Expose payment gateway on port 7000
    networks:
      - app-network
    env_file:
      - ./Payment-Gateway/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: cake-store-mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongodb-data:/data/db  # Persistent storage for MongoDB data
    networks:
      - app-network

volumes:
  mongodb-data:
    driver: local

networks:
  app-network:
    driver: bridge


    
