// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('EmptyFieldSignup1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('EmptyFieldSignup1', async function() {
    await driver.get("http://localhost:5174/register")
    await driver.manage().window().setRect({ width: 856, height: 824 })
    await driver.findElement(By.name("email")).sendKeys("nijayeeumaya9@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("000")
    await driver.findElement(By.css(".row:nth-child(6) > .col:nth-child(2) .form-control")).click()
    await driver.findElement(By.css(".row:nth-child(6) > .col:nth-child(2) .form-control")).sendKeys("000")
    await driver.findElement(By.css(".space > input")).click()
  })
})
