// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('EditProfile1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('EditProfile1', async function() {
    await driver.get("http://localhost:5174/Update")
    await driver.manage().window().setRect({ width: 856, height: 824 })
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Nijayeeeeeeeeeeee")
    await driver.findElement(By.css(".btn")).click()
  })
})
