// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('UpdateButton1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('UpdateButton1', async function() {
    await driver.get("http://localhost:5174/profile")
    await driver.manage().window().setRect({ width: 856, height: 824 })
    await driver.findElement(By.linkText("Update")).click()
  })
})
