// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test8', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test8', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 799, height: 816 })
    await driver.findElement(By.linkText("Home")).click()
    await driver.findElement(By.linkText("Cart")).click()
    await driver.findElement(By.css("li:nth-child(3) > a")).click()
    await driver.findElement(By.css("li:nth-child(3) > a")).click()
    await driver.findElement(By.linkText("Profile")).click()
    await driver.findElement(By.css("li:nth-child(3) > a")).click()
    await driver.findElement(By.css("li:nth-child(2)")).click()
    await driver.findElement(By.linkText("Cart")).click()
    await driver.findElement(By.linkText("Home")).click()
  })
})
