// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TestingFooter', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TestingFooter', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 799, height: 816 })
    await driver.findElement(By.css(".col-md-3 > p:nth-child(2) > .text-reset")).click()
    await driver.findElement(By.css(".col-md-3 > p:nth-child(3) > .text-reset")).click()
    await driver.findElement(By.css(".col-md-3 > p:nth-child(4) > .text-reset")).click()
    await driver.findElement(By.css(".col-md-3 > p:nth-child(2) > .text-reset")).click()
  })
})
