// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ValidForgotPW1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ValidForgotPW1', async function() {
    await driver.get("http://localhost:5174/login")
    await driver.manage().window().setRect({ width: 856, height: 824 })
    await driver.findElement(By.linkText("Forget Password")).click()
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    await driver.findElement(By.linkText("Forget Password")).click()
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
  })
})
