// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://localhost:5174/login")
    await driver.manage().window().setRect({ width: 798, height: 824 })
    await driver.findElement(By.css(".field:nth-child(2) > input")).sendKeys("nijayeeumaya9@gmail.com")
    await driver.findElement(By.css(".pass-key")).sendKeys("000")
    await driver.findElement(By.css("input:nth-child(1)")).click()
  })
})
